feat: disk check and feishu alert
Byzanteam/operations pull request #5
Opened 2022-12-28 09:29 UTC by YkeLit

现在项目上很多服务器出现硬盘空间占满后服务无响应情况，写了个自动报警的脚本来监控硬盘空间情况

2022-12-29 06:34 UTC, fahchen requested changes
- [x] 把 uninstall 做一下
- [ ] 做成一个 service 会不会好一些？

2022-12-29 07:53 UTC, fahchen requested changes

2022-12-29 07:53 UTC, fahchen commented on disk_check/README.md
> +```
用一个 script，通过参数去控制 install 或者 uninstall，默认是 install

2022-12-29 07:53 UTC, fahchen commented on disk_check/install_disk_check.sh
> +echo "0 9-22 * * * /bin/bash /opt/disk_check/disk_check.sh > /dev/null 2>&1" >> /var/spool/cron/root
只保留一个 script 文件哈

2022-12-29 07:54 UTC, fahchen commented on disk_check/README.md
> +```
install 之前检查一下是否存在，如果存在就报错或者给提示

2022-12-29 07:57 UTC, YkeLit commented on disk_check/install_disk_check.sh
> +echo "0 9-22 * * * /bin/bash /opt/disk_check/disk_check.sh > /dev/null 2>&1" >> /var/spool/cron/root
好吧 我看下怎么做

2022-12-29 10:34 UTC, YkeLit commented on disk_check/install_disk_check.sh
> +echo "0 9-22 * * * /bin/bash /opt/disk_check/disk_check.sh > /dev/null 2>&1" >> /var/spool/cron/root
现在改好了

2022-12-30 02:26 UTC, fahchen requested changes

2022-12-30 02:26 UTC, fahchen commented on disk_check/disk_check.sh
> +
这两个 script 问价合并成一个吧

2022-12-30 02:55 UTC, YkeLit commented on disk_check/disk_check.sh
> +
放到一起是不是耦合度太高了

2022-12-30 05:31 UTC, fahchen commented on disk_check/disk_check.sh
> +
没有哈，单文件安装比较好，多个文件会有安装下载多个文件的问题

2022-12-30 12:49 UTC, YkeLit commented on disk_check/disk_check.sh
> +
合上了

2023-01-03 03:55 UTC, fahchen reviewed
看下这个好用不？
https://github.com/megaease/easeprobe

2023-01-03 03:55 UTC, fahchen commented on disk_check/deploy_control.sh
> +#!/bin/env sh
这个文件名改成 `disk_check/install.sh`

2023-01-03 03:55 UTC, fahchen commented on disk_check/deploy_control.sh
> +		echo "0 9-22 * * * /bin/bash /opt/disk_check/disk_check.sh > /dev/null 2>&1" >> /var/spool/cron/root
`/opt/disk_check/disk_check.sh` 这个路径有点重复
这个如何？ `/opt/disk_check/monitor.sh`

2023-01-03 07:12 UTC, YkeLit commented on disk_check/deploy_control.sh
> +		echo "0 9-22 * * * /bin/bash /opt/disk_check/disk_check.sh > /dev/null 2>&1" >> /var/spool/cron/root
ok

2023-01-03 07:12 UTC, YkeLit commented on disk_check/deploy_control.sh
> +#!/bin/env sh
ok

2023-01-03 07:14 UTC, YkeLit commented on disk_check/deploy_control.sh
> +#!/bin/env sh
这个工具感觉可以但是有不是很必须，监控软件自带有 alert ，自己写的脚本也可以把发送信息的那一段命令提取出来复用

2023-01-03 07:28 UTC, fahchen requested changes
用可交互的形式来让用户输入或确认配置

2023-01-03 07:28 UTC, fahchen commented on disk_check/install.sh
> +	install)
如果 `install`，但没有提供 webhook 直接报错吧

2023-01-03 07:28 UTC, fahchen commented on disk_check/install.sh
> +ip=`hostname -I | awk '{print $1}'`
这个 IP 拿到的是内网的 IP 感觉没啥用呀？
这里是不是我们在 install 的时候，填入 hostname 等信息，这样我们才能识别得出来？

2023-01-03 07:28 UTC, fahchen commented on disk_check/README.md
> +> 使用前建议修改 `disk_check.s`h 脚本如下变量以获得更准确的信息：
```suggestion
> 使用前建议修改 `disk_check.sh` 脚本如下变量以获得更准确的信息：
```

2023-01-03 07:28 UTC, fahchen commented on disk_check/README.md
> +> `ip=""`
这个可以作为 config 存储在旁边，或者通过交互或者环境变量的形式让用户输入

2023-01-03 08:53 UTC, YkeLit commented on disk_check/install.sh
> +ip=`hostname -I | awk '{print $1}'`
内网的IP才有用吧，政务云里只有查下内网IP才知道是哪个机器，他们出口IP都是一样的

2023-01-03 09:17 UTC, fahchen commented on disk_check/install.sh
> +ip=`hostname -I | awk '{print $1}'`
给一个我们的标识在里面吧，在我们的服务器列表里面也维护一下

2023-01-12 04:15 UTC, fahchen requested changes

2023-01-12 04:15 UTC, fahchen commented on disk_check/install.sh
> +cat > monitor.sh << END
你配置下编辑器，行尾的空格显示一下
```suggestion
cat > monitor.sh << END
```

2023-01-12 04:15 UTC, fahchen commented on disk_check/install.sh
> +		cd /opt/disk_check/
```suggestion
		cd /opt/disk_check/
```

2023-01-12 04:16 UTC, fahchen commented on disk_check/install.sh
> +cat > env.sh << END
配置文件不用做成脚本哇

2023-01-12 04:19 UTC, fahchen requested changes
Google 的 bash 的 style guide 看一下，把格式调整下
https://google.github.io/styleguide/shellguide.html

2023-01-12 04:20 UTC, fahchen commented on disk_check/install.sh
> +cat > env.sh << END
这里应该有缩进
```suggestion
    cat > env.sh << END
```

2023-01-12 05:03 UTC, YkeLit commented on disk_check/install.sh
> +cat > env.sh << END
统一文件格式

2023-01-12 06:41 UTC, fahchen commented on disk_check/install.sh
> +cat > env.sh << END
@vanppo 你觉得呢

2023-01-12 07:28 UTC, vanppo commented on disk_check/install.sh
> +cat > env.sh << END
感觉没什么必要搞个配置文件呢 hostname 和 ip 可以通过命令去获取嘛
就剩下 webhook 和 tag 可以作为脚本的参数吧

2023-01-12 11:41 UTC, YkeLit commented on disk_check/install.sh
> +cat > env.sh << END
还是成配置文件把，方便后面去更改 value，hostname 和 IP 是通过命令获取的

2023-01-12 11:42 UTC, YkeLit commented on disk_check/install.sh
> +cat > env.sh << END
写成这样是因为这个脚本生成的脚本缩进不会那么奇怪，而且 END 结束符前面不能有空格和 TAB 不然识别不到结束符

2023-01-12 12:48 UTC, fahchen commented on disk_check/install.sh
> +cat > env.sh << END
只是这一行差缩进

2023-01-13 03:31 UTC, YkeLit commented on disk_check/install.sh
> +cat > env.sh << END
好的已经改了

2023-01-13 03:57 UTC, vanppo reviewed
还有就是按照安装的步骤拆分下函数，然后目录结构稍微规范点的话应该是 /opt/monitor/bin/disk.sh

2023-01-13 03:57 UTC, vanppo commented on disk_check/install.sh
> +deploy=${DEPLOY:-'install'}
把脚本内容整个放到 `{}` 中，防止因为网络原因只有部分脚本被执行

2023-01-13 03:57 UTC, vanppo commented on disk_check/install.sh
> +critical=90
这些配置我还是觉得做成参数用起来会比较舒服一点
```shell
bash <(curl -sL url) --critical=85 --tag=test --webhook=webhook
curl -sL url | sh -s - --critical=85 --tag=test --webhook=webhook
```

2023-01-13 06:09 UTC, YkeLit commented
再看看吧 @fahchen @vanppo

2023-01-13 06:49 UTC, vanppo commented on disk_check/install.sh
> +set -eu
```suggestion
set -euo pipefail
```

2023-01-13 06:49 UTC, vanppo commented on disk_check/install.sh
> +			[ -d /opt/monitor ] || mkdir -p /opt/monitor/bin && cd /opt/monitor/bin
```suggestion
			[ -d /opt/monitor/bin ] || mkdir -p /opt/monitor/bin && cd /opt/monitor/bin
```

2023-01-13 07:40 UTC, YkeLit commented on disk_check/install.sh
> +set -eu
这个时什么意思呀波哥

2023-01-13 08:02 UTC, vanppo commented on disk_check/install.sh
> +set -eu
包含管道的命令，如果某个命令失败了就会认为整个命令失败了，默认情况下只要最后一个命令成功了，就会认为整个都正确的。

2023-04-14 10:58 UTC, closed without merging